---
global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 1m
scrape_configs:
  - job_name: oncall-dns-scrape
    dns_sd_configs:
      - names:
          - oncall-web
        type: A
        port: 8100
        refresh_interval: 30s

